config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    root 'welcome#browse', as: :authenticated
    get '/profile' => 'users#show'
  end
  resources :body_parts, only: [:show] do
    resources :injuries, except: [:index]
  end

  resources :injuries, only: [] do
    resources :activities, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end

  resources :topics, only: [] do
    resources :posts, only: [:create, :destroy]
  end

  resources :posts, only: [] do
    resources :favorites, only: [:create, :destroy]
    post '/helpful' => 'votes#helpful', as: :helpful
    post '/unhelpful' => 'votes#unhelpful', as: :unhelpful
  end


  root to: 'welcome#index'
  get '/about' => 'welcome#about'
  get '/disclaimer' => 'welcome#disclaimer'
  get '/browse' => 'welcome#browse'
  get '/search' => 'searches#show'
  resources :activities, only: [:show]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def disclaimer
  end

  def browse
    @body_parts = BodyPart.all
    @feed_items = FeedItem.first(10)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.haml
.container
  .row
    .col-md-8

      %h1 About Injury Forum
      %br/
      %h4.info-spacing Injury Forum was created for everyone and anyone who has ever had a musculoskeletal injury to share their experiences and knowledge about injury and recovery in the hope to aid others in their journey to recovery.

      %h4.info-spacing The purpose of this site is to serve as a repository for the public's knowledge about all things injury and recovery. The hope is that users will be able to provide others with the vital information that they need to make complete recoveries.

      %h4.info-spacing With doctors' time at an ever increasing premium, there is more and more responsibility placed upon us, the patients, to take responsibility for our own recovery.  Once you have a diagnosis and a treatment plan, you are often sent off to a therapist or on your own to execute the steps necessary to get you back to full health.

      %h4.info-spacing This is the place to share and find the basic information about your injury, to share and find helpful resources, be it books, blogs, pamphlets, or videos, to share and find inspirational stories about recovery, and to share and find alternative exercises or plans for recovery.

      %h4.info-spacing The only thing missing is you, the compassionate, knowledgeable users to provide information for one another.

app/views/welcome/browse.html.haml
.container
  .row
    .col-md-2
      .btn-group-vertical.container-fluid
        - @body_parts.each do |part|
          = link_to "#{part.name}", body_part_path(part), class: 'btn btn-default'
    .col-md-8
      %h1 Site Activity
      - @feed_items.each do |feed_item|
        .media
          .media-body

            %h3
              %span.glyphicon{class: "#{feed_item_glyphicon(feed_item.trackable)}", "aria-hidden" => true}
              = feed_item.user.username
              = display_feed_item(feed_item)

app/views/welcome/disclaimer.html.haml
.container
  .row
    .col-md-8
      %h1 Injury Forum Disclaimer
      %h4.info-spacing All information on this site was provided by users like yourself.  As such, Injury Forum advises that you consult a medical professional before performing any exercise or following any treatment plan that you find on the site.
      %h4.info-spacing The content on the site is meant for use as reference.  Injury Forum accepts no responsibility for any further injuries incurred while following the advice of others on this site.  No medical treatment or rehabilitation protocol should be initiated without consulting a medical professional first.
      %br/
      %h2 A Word of Reason
      %h4.info-spacing Please practice safety first.  We want to help each other recover from injuries, first and foremost.  That said, while it is good to be enthusiastic and open-minded to different approaches to recovery, a certain amount of practicality and caution needs to be applied when dealing with injuries and other sensitive ailments.
      %h4.info-spacing May you have a steady and complete recovery and maintain a pragmatic approach to preventing recurrences.

app/views/welcome/index.html.haml
.jumbotron
  .container
    %h1 Injury Forum
    %p Find and share information concerning your recovery
    %p
      = link_to "Register", new_user_registration_path, class:"btn btn-primary", role: "button"
      or
      = link_to "Login", new_user_session_path, class:"btn btn-default", role: "button"
.container
  .row
    .col-md-8
      .media
        .media-body
          %h4 Welcome to Injury Forum!
          %p Injury Forum is a forum based site where users can share anything and everything about injuries and recovery.  Use the search feature to look for the injury that you are concerned about or create a new forum for that injury if one doesn't exist.
          %p
            Everyone is free to browse the site and read the content available.  However, if you want to contribute to the information on the site, you need to
            = link_to "create an account.", new_user_registration_path

          %p Registered users have the ability to create new forums for injuries, create posts to the forums, share how they incurred an injury, track the injuries and posts that they find most helpful in their user profile, and more...
          %p We hope that Injury Forum can help every user find the information they need to make a complete recovery!
    .col-md-4
      .media
        .media-body
          %h4 Browse the site
          %p
            Skip registration for now and see what the site has to offer before deciding to join the discussion.
            %br/
            %br/
            = link_to "Browse", browse_path, class:"btn btn-primary"