config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    root 'welcome#browse', as: :authenticated
    get '/profile' => 'users#show'
  end
  resources :body_parts, only: [:show] do
    resources :injuries, except: [:index]
  end

  resources :injuries, only: [] do
    resources :activities, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end

  resources :topics, only: [] do
    resources :posts, only: [:create, :destroy]
  end

  resources :posts, only: [] do
    resources :favorites, only: [:create, :destroy]
    post '/helpful' => 'votes#helpful', as: :helpful
    post '/unhelpful' => 'votes#unhelpful', as: :unhelpful
  end


  root to: 'welcome#index'
  get '/about' => 'welcome#about'
  get '/disclaimer' => 'welcome#disclaimer'
  get '/browse' => 'welcome#browse'
  get '/search' => 'searches#show'
  resources :activities, only: [:show]
end

app/models/injury.rb
class Injury < ActiveRecord::Base
  include PgSearch
  multisearchable  :against => [:name]
  belongs_to :user
  belongs_to :body_part
  has_many :injury_symptoms, dependent: :destroy
  has_many :symptoms, through: :injury_symptoms
  has_many :topics, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :favorites, as: :favoriteable, dependent: :destroy
  has_many :feed_items, as: :trackable, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy
  accepts_attachments_for :images, attachment: :file

  before_create :injury_capitalize

  validates :name, presence: true, length: {minimum: 10}, uniqueness: {case_sensitive: false}
  validates :description, presence: true, length: {minimum: 30}

  def generate_topics
     ["Description", "Recovery Stories", "Treatment Plans", "Prevention", "Q&A", "Recovery Methods", "Resources"].each do |topic|
      topics.create!(name: topic)
    end
  end
  def top_five_activities_array
    self.activities.group(:name).count.sort{|x,y| x[1] <=> y[1]}.reverse.first(5)
  end

  def description_post_highest_score
    topics.first.posts.order(:score).last
  end

  def update_description
    initial_description = self.description
    update_attribute(:description, description_post_highest_score.body)
    if initial_description == self.description
      return false
    else
      return true
    end
  end

  private
  def injury_capitalize
    self.name = name.split.map {|s| s.capitalize}.join(" ")
  end




end

app/controllers/injuries_controller.rb
class InjuriesController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def show
    @body_part = BodyPart.find(params[:body_part_id])
    @injury = Injury.find(params[:id])
    @top_activities = @injury.top_five_activities_array
    @post = @injury.topics.first.posts.where(body: @injury.description).first
  end

  def new
    @body_part = BodyPart.find(params[:body_part_id])
    @injury = @body_part.injuries.new
    @symptoms = Symptom.all
  end

  def create
    @body_part = BodyPart.find(params[:body_part_id])
    @injury = @body_part.injuries.new(injury_params)
    @injury.user = current_user
    if @injury.save
      @injury.generate_topics
      post = @injury.topics.first.posts.create!(title: "#{@injury.name} original description", body: @injury.description, user: current_user)
      post.votes.create!(user: current_user, value: 1)
      AddUserFeedItem.call(current_user, action_name, @injury)
      flash[:notice] = "New #{@body_part.name} injury: #{@injury.name} created."
      redirect_to [@body_part, @injury]
    else
      flash[:error] = "An error occurred. Please try again."
      render :new
    end
  end

  def edit
    @body_part = BodyPart.find(params[:body_part_id])
    @injury = @body_part.injuries.find(params[:id])
  end

  def update
    @body_part = BodyPart.find(params[:body_part_id])
    @injury = @body_part.injuries.find(params[:id])
    post = Post.where(body: @injury.description).first
    if @injury.update_attributes(injury_params)
      post.update_attribute(:body, @injury.description)
      flash[:notice] = "Update succeeded."
      redirect_to [@body_part, @injury]
    else
      flash[:error] = "An error occurred. Try updating again."
      render :edit
    end
    if @injury.description_post_highest_score != post
      @injury.update_description
    end
  end

  def destroy
    @body_part = BodyPart.find(params[:body_part_id])
    @injury = @body_part.injuries.find(params[:id])
    if @injury.destroy
      flash[:notice] = "Injury deleted."
      redirect_to [@body_part, @injury]
    else
      flash[:error] = "An error occurred. Try again."
      render :show
    end
  end

  private
  def injury_params
    params.require(:injury).permit(:name, :description, symptom_ids: [], images_files: [])
  end


end

app/helpers/injuries_helper.rb
module InjuriesHelper
end

app/views/injuries/_injury.html.haml
.panel.panel-info
  .panel-heading
    %b= link_to "#{injury.name}", body_part_injury_path(injury.body_part, injury)
    -if user_can_edit?(injury)
      = link_to "Edit", edit_body_part_injury_path(injury.body_part, injury), class: 'pull-right', data: {"no-turbolink" => true}
  .panel-body
    %b Description:
    %br/
    = truncate(injury.description, length: 150)
    = "..."
    %br/
    %b Symptoms:
    %br/
    = injury.symptoms.pluck(:name).join(", ")

app/views/injuries/edit.html.haml
.container
  %h1 Edit Injury Page
  .row
    .col-md-8
      %p Guidelines for injury forums
      %ul
        %li Please use the format: "Common Name (Medical Term)"
        -# The description will ultimately be updated from an description topic post with the highest number of votes
        %li You may update the description for the injury. Please be considerate if the current description was not posted by you.

      = form_for [@body_part, @injury] do |f|
        - if @injury.errors.any?
          .alert.alert-danger
            %h4= pluralize(@injury.errors.count, "error")
            %ul
              - @injury.errors.full_messages.each do |msg|
                %li= msg
        = form_group_tag(@injury.errors[:name]) do
          = f.label :name
          = f.text_field :name, class: 'form-control', placeholder: "Common Name (Medical Term)"
        .form-group
          = label_tag 'injury-symptoms', 'Symptoms'
          %br
          = select_tag 'injury[symptom_ids][]', options_for_select(Symptom.all.map {|s| [s.name, s.id, should_be_selected(s, @injury)] }), class: 'selectpicker', multiple: '', "data-live-search" => true, "data-width" => '100%'
        = form_group_tag(@injury.errors[:description]) do
          = f.label :description
          = f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter description of injury here. Use guidelines above."
        -# TODO: add field for accepting activities

        .form-group
          = f.submit "Update Forum", class: 'btn btn-primary'

app/views/injuries/new.html.haml
.container
  %h1 New Injury
  .row
    .col-md-8
      %p Guidelines for creating a new injury forum
      %ul
        %li Ensure that a forum for your injury does not exist
        %li Please use the format: "Common Name (Medical Term)"
        %li Provide a description for the injury. Consider including:
        %ul
          %li Causes, diagnosis,symptoms, average recovery time
      = form_for [@body_part, @injury] do |f|
        - if @injury.errors.any?
          .alert.alert-danger
            %h4= pluralize(@injury.errors.count, "error")
            %ul
              - @injury.errors.full_messages.each do |msg|
                %li= msg
        = form_group_tag(@injury.errors[:name]) do
          = f.label :name
          = f.text_field :name, class: 'form-control', autofocus: true, placeholder: "Common Name (Medical Term)"

        .form-group
          = label_tag 'injury_symptoms', 'Symptoms'
          %br
          = select_tag 'injury[symptom_ids][]', options_for_select(Symptom.all.map { |s| [s.name, s.id]}, params[:injury] ? params[:injury][:symptom_ids] : ''), class: 'selectpicker', multiple: '', "data-live-search" => true, "data-width" => "100%"
        = form_group_tag(@injury.errors[:description]) do
          = f.label :description
          = f.text_area :description, rows: 8, class: 'form-control', placeholder: 'Enter description of injury here. Use guidelines above.'
        .form-group
          = f.label :images_files
          = f.attachment_field :images_files, multiple: true

        -# TODO: add field for accepting activities
        .form-group
          = f.submit "Create Forum", class: 'btn btn-primary'

app/views/injuries/show.html.haml
.container
  .row
    .col-md-8
      .jumbotron
        %h2
          = @injury.name
          .pull-right.js-favorite-injury
            = render partial: 'favorites/favorite', locals: {favoriteable: @injury}
        %small
          %p
            %b Body part:
            = link_to "#{@body_part.name}", body_part_path(@body_part)
          %p
            %b Symptoms:
            %br/
            = @injury.symptoms.pluck(:name).join(", ")
          %p#injury_description
            %b Description:
            %br/
            = @injury.description
          - if !@injury.images.empty?
            %p
              %b Images:
              %br/

              - @injury.images.each.with_index do |image, i|
                = link_to "image ##{i + 1}", attachment_url(image, :file), target: "_blank"
                %br/
          -if user_can_edit?(@injury)
            %p.pull-right= link_to "Edit", edit_body_part_injury_path(@body_part, @injury), data: {"no-turbolink" => true}
    .col-md-4
      %h3 Top Related Activities
      %ol.js-activities
        - @top_activities.each do |name, count|
          %li
            = link_to name, activity_path(Activity.where(name: name).first)
            = ": " + count.to_s
      %p What activity or sport were you participating in when you incurred this injury?
      .new-activity
        = render partial: 'activities/form', locals: {injury: @injury, activity: @injury.activities.new}
      %br/
      - if @post
        #js_description_voter
          What did you think of this description? &nbsp;
          = render partial: 'votes/voter', locals: {post: @post}

.containter
  .row
    .col-md-1
    .col-md-8
      %ul.nav.nav-tabs
        -@injury.topics.each do |topic|
          %li{:role => "presentation"}
            = link_to "#{topic.name}", "##{id_friendly(topic.name)}", "aria-controls" => "#{topic.name}", "data-toggle" => "tab", role: "tab"
      .tab-content
        -@injury.topics.each do |topic|
          .tab-pane{:id => "#{id_friendly(topic.name)}", :role => "tabpanel"}
            = render partial: 'topics/display', locals: {injury: @injury, topic: topic}

app/views/injuries/show.js.erb
$(".topic-" + <%= params[:topic_id] %> + "-pagination").html("<%= j(render partial: 'posts/post', collection: @posts = Post.where(topic_id: params[:topic_id]).where.not(id: nil).paginate(:page => params[:page], :per_page => 10))%><%= j(js_will_paginate @posts, class:'col-md-8', :params => {topic_id: params[:topic_id]})%>")