config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    root 'welcome#browse', as: :authenticated
    get '/profile' => 'users#show'
  end
  resources :body_parts, only: [:show] do
    resources :injuries, except: [:index]
  end

  resources :injuries, only: [] do
    resources :activities, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end

  resources :topics, only: [] do
    resources :posts, only: [:create, :destroy]
  end

  resources :posts, only: [] do
    resources :favorites, only: [:create, :destroy]
    post '/helpful' => 'votes#helpful', as: :helpful
    post '/unhelpful' => 'votes#unhelpful', as: :unhelpful
  end


  root to: 'welcome#index'
  get '/about' => 'welcome#about'
  get '/disclaimer' => 'welcome#disclaimer'
  get '/browse' => 'welcome#browse'
  get '/search' => 'searches#show'
  resources :activities, only: [:show]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:title, :body]
  belongs_to :topic
  belongs_to :user
  has_many :favorites, as: :favoriteable, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :feed_items, as: :trackable, dependent: :destroy


  alias_attribute :name, :title
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: {minimum: 5}

  def update_score
    new_score = votes.inject(0){|sum, vote| sum += vote.value} + (1 - (1.0 / votes.count))
    update_attribute(:score, new_score)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.new(post_params)
    @post.user = current_user
    @new_post = @topic.posts.new

    if @post.save
      @post.votes.create!(user: @post.user, value: 1)
      AddUserFeedItem.call(current_user, action_name, @post)
      flash[:notice] = "Post created successfully."
    else
      flash[:error] = "An error occurred. Please try posting again."
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post deleted."
    else
      flash[:error] = "An error occurred. Try deleting the post again."
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
%h3 New Post
= form_for [topic, post], remote: true do |f|
  .form-group
    = f.text_field :title, class: 'form-control', placeholder: "Title..."
  .form-group
    = f.label :body, "Post Content"
    %br/
    = f.text_area :body, class: 'form-control', placeholder: "Enter post content here...", rows: 6
  .form-group
    = f.submit "Create Post", class: 'btn btn-primary'

app/views/posts/_post.html.haml
= div_for(post, class: "col-md-8 panel panel-default") do
  .panel-heading
    %h4.panel-title.post-header
      = post.title
      %small.pull-right
        - if post.user == current_user
          %a{href: '/profile'}
            %span.glyphicon.glyphicon-user{"aria-hidden" => true}
            = post.user.username
        - else
          %i.glyphicon.glyphicon-user{"aria-hidden" => true}
          = post.user.username

  .panel-body
    %p.post-body= post.body
  .panel-footer
    = div_for(post, class: 'js-favorite-post') do
      = render partial: 'favorites/favorite', locals: {favoriteable: post}

    = div_for(post, class: 'js-votes') do
      = render partial: 'votes/voter', locals: {post: post}
    .pull-right.post-delete= link_to "Delete", topic_post_path(post.topic, post), method: :delete, remote: true

app/views/posts/create.js.erb
<% if @post.valid? %>
  var $append_post_loc = $(".topic-" + <%= @topic.id %> + "-pagination > div").last();
  if ($append_post_loc.length) {
    $($append_post_loc).after("<%= escape_javascript(render(@post))%>");
  } else {
    var $append_post_loc = $(".topic-" + <%= @topic.id %> + "-pagination");
    $($append_post_loc).append("<%= j(render(@post))%>");
  }

  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' 'data-dismiss'='alert'>&times;</button><%= flash[:notice] %></div>");
  $("#topic-" + <%= @topic.id %> + "-new-post").html("<%= escape_javascript(render partial: 'posts/form', locals: {topic: @topic, post: @new_post})%>");
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class='close' 'data-dismiss'='alert'>&times;</button><%= flash[:error] %></div>");
  $("#topic-" + <%= @topic.id %> + "-new-post").html("<%= escape_javascript(render partial: 'posts/form', locals: {topic: @topic, post: @post})%>");
<% end %>

app/views/posts/destroy.js.erb
<% if @post.destroyed? %>
  $('#post_' +<%= @post.id %>).hide();
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>")
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class'close' data-dismiss='alert'>&times;</button><%= flash[:error]%></div>");
<% end %>