config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    root 'welcome#browse', as: :authenticated
    get '/profile' => 'users#show'
  end
  resources :body_parts, only: [:show] do
    resources :injuries, except: [:index]
  end

  resources :injuries, only: [] do
    resources :activities, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end

  resources :topics, only: [] do
    resources :posts, only: [:create, :destroy]
  end

  resources :posts, only: [] do
    resources :favorites, only: [:create, :destroy]
    post '/helpful' => 'votes#helpful', as: :helpful
    post '/unhelpful' => 'votes#unhelpful', as: :unhelpful
  end


  root to: 'welcome#index'
  get '/about' => 'welcome#about'
  get '/disclaimer' => 'welcome#disclaimer'
  get '/browse' => 'welcome#browse'
  get '/search' => 'searches#show'
  resources :activities, only: [:show]
end

app/views/layouts/_injury_nav.html.haml
.container
  %ul.nav.nav-pills
    %li{:role => "presentation", :class => "dropdown navbar-btn"}
      %a{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button", :class => "dropdown-toggle"}
        Body Parts
        %span.caret

      %ul.dropdown-menu
        - BodyPart.all.each do |body_part|
          %li= link_to "#{body_part.name}", body_parts_show_path(body_part)

app/views/layouts/_messages.html.haml
.flash
  - flash.each do |key, value|
    %div{ class: "alert alert-#{bootsrap_key(key)}"}
      %a.close{ href: "#", "data-dismiss" => "alert"} &times;
      %ul
        %li
          = value

app/views/layouts/_navbar.html.haml
.navbar-header
  .navbar-brand= link_to "Injury Forum", root_path
%ul.nav.navbar-nav.navbar-left
  %li= link_to "About", about_path, class:'root-link-nav'
  %li= link_to "Disclaimer", disclaimer_path, class:'root-link-nav'
.navbar-right
  = form_tag search_path, method: :get, class: 'navbar-form navbar-left' do
    .form-group
      = text_field_tag :query, nil, class: 'form-control', placeholder: 'Search'

      = submit_tag "Search", class: 'btn btn-default'

  - unless user_signed_in?
    = link_to "Login", new_user_session_path, class: "btn btn-default navbar-btn"
    = link_to "Register", new_user_registration_path, class: "btn btn-primary navbar-btn"
  -else
    %h4.navbar-text= link_to "#{current_user.username}", profile_path
    = link_to "Logout", destroy_user_session_path, class: "btn btn-default navbar-btn", method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title InjuryForum
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.9.3/css/bootstrap-select.min.css'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.9.3/js/bootstrap-select.js'
    = csrf_meta_tags
  %body
    .navbar.navbar-default.navbar-static-top{:role => "navigation"}
      .container
        = render 'layouts/navbar'
    .container.flash-container
      = render 'layouts/messages'
    = yield